services:
  postgres:
    container_name: postgres-dev
    image: postgres:15.6-alpine3.19
    restart: unless-stopped
    ports:
      - "54522:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - interconnect


volumes:
  postgres_data: {}

networks:
  interconnect:
    driver: bridge
